tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: sysadmin
      database: dbt_db
      schema: dev
      warehouse: dbt_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: sysadmin
      database: dbt_db
      schema: prod
      warehouse: dbt_wh
